Random order generation
ALLAN-DIP/baseline_bots pull request #39
Opened 2022-09-29 02:04 UTC by kkahadze

Fixes #25

2022-09-29 02:13 UTC, trigaten requested changes
Great docstrings!

A bit of work to be done on type hints. Also, I would like to see more regular (#) comments throughout the code.

Finally, please move your functions into a new file.

2022-09-29 02:13 UTC, trigaten commented on src/baseline_bots/utils.py
> +def random_orders(orders: list):
`list` should be `List`

2022-09-29 02:13 UTC, trigaten commented on src/baseline_bots/utils.py
> +# fmt: off
Can you provide some minimal comments which explain these constants.

2022-09-29 02:13 UTC, trigaten commented on src/baseline_bots/utils.py
> +def orders_correspondence(orders: list) -> (list):
What is (list)?

2022-09-29 02:16 UTC, trigaten commented on src/baseline_bots/utils.py
> +def random_movement(order, chance_of_move=0.3):
type hint order

2022-09-29 02:17 UTC, trigaten commented on tests/utils_test.py
> +        ord =  [(('FRA', "AMY", 'PAR'), 'BLD')]
provide comments that explain the test cases

2022-09-30 20:38 UTC, trigaten requested changes

2022-09-30 20:38 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +# the comments below signal the formatter not to expand these dicts to multiple lines
Sorry, I meant comments to describe ADJACENCY, TYPES, and COMBOS. What is the point of each of these constants?

2022-09-30 20:38 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +def random_orders(orders: List):
Need return type hint

2022-09-30 20:38 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +        new = orders
Please rename the variable `new` to be more descriptive.

2022-09-30 20:38 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +def random_convoy_to(order: tuple) -> tuple:
`tuple` should be `Tuple`. Import the `Tuple` type.

2022-09-30 20:38 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +    assert amy_type == "AMY" and flt_type == "FLT"
Make this return an intelligent error string if the assertion fails

2022-09-30 20:38 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +def random_support(order: tuple) -> tuple:
Again, correct `tuple`

2022-09-30 20:38 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +    if len(order) <= 3:  # if it is supporting to hold
# comments throughout would be good

2022-09-30 20:38 UTC, trigaten commented on tests/randomize_dipnet_test.py
> +        # input into the order randomizer, they come out differnent
I would like to see a seeded trial, where you compare the output to an actual expected string

2022-09-30 20:38 UTC, trigaten commented on tests/randomize_dipnet_test.py
> +        # input into the order randomizer, they come out differnent
also different*

2022-10-02 00:42 UTC, trigaten commented
Please resolve merge conflicts and add a sphinx page for your functions.

2022-10-02 21:31 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +def randomize(order: tuple) -> tuple:
Fix all of the tuple -> Tuple problems

2022-10-02 21:32 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +def random_build(order: Tuple) -> Tuple:
What?

2022-10-02 21:34 UTC, trigaten commented on src/baseline_bots/randomize_dipnet.py
> +def randomize_joiner(order: str) -> str:
Can you rename this function to smtg more intelligible like `randomize_order`?

2022-10-02 22:03 UTC, kkahadze commented on src/baseline_bots/randomize_dipnet.py
> +def random_build(order: Tuple) -> Tuple:
I fixed that

2022-10-03 00:42 UTC, trigaten commented
Can you rename the file name to randomize_order

2022-10-03 00:42 UTC, trigaten commented on tests/randomize_dipnet_test.py
> +class TestUtils:
rename this appropriately

2022-10-03 01:13 UTC, trigaten approved these changes
Great job Konstantine! The code looks wonderful. 

Take a look at the recommendations here: https://allan-dip.github.io/baseline_bots/development/#pushing-code

2022-10-03 01:13 UTC, merged